const Types = {
  GET_CLIENTES_REQUEST: '@clientes/GET_CLIENTES_REQUEST',
  GET_CLIENTES_SUCCESS: '@clientes/GET_CLIENTES_SUCCESS',
  GET_CLIENTES_FAILURE: '@clientes/GET_CLIENTES_FAILURE',

  CREATE_CLIENTE_REQUEST: '@clientes/CREATE_CLIENTE_REQUEST',
  CREATE_CLIENTE_SUCCESS: '@clientes/CREATE_CLIENTE_SUCCESS',
  CREATE_CLIENTE_FAILURE: '@clientes/CREATE_CLIENTE_FAILURE',

  UPDATE_CLIENTE_REQUEST: '@clientes/UPDATE_CLIENTE_REQUEST',
  UPDATE_CLIENTE_SUCCESS: '@clientes/UPDATE_CLIENTE_SUCCESS',
  UPDATE_CLIENTE_FAILURE: '@clientes/UPDATE_CLIENTE_FAILURE',

  DELETE_CLIENTE_REQUEST: '@clientes/DELETE_CLIENTE_REQUEST',
  DELETE_CLIENTE_SUCCESS: '@clientes/DELETE_CLIENTE_SUCCESS',
  DELETE_CLIENTE_FAILURE: '@clientes/DELETE_CLIENTE_FAILURE',
};

export default Types;
