const types = {
  // FILTER
  FILTER_AGENDAMENTOS: '@agendamento/FILTER',
  FILTER_AGENDAMENTOS_SUCCESS: '@agendamento/FILTER_SUCCESS',
  FILTER_AGENDAMENTOS_ERROR: '@agendamento/FILTER_ERROR',
  UPDATE_AGENDAMENTOS: '@agendamento/UPDATE',

  // CREATE
  CREATE_AGENDAMENTO: '@agendamento/CREATE',
  CREATE_AGENDAMENTO_SUCCESS: '@agendamento/CREATE_SUCCESS',
  CREATE_AGENDAMENTO_ERROR: '@agendamento/CREATE_ERROR',

  // UPDATE ONE
  UPDATE_AGENDAMENTO: '@agendamento/UPDATE_ONE',
  UPDATE_AGENDAMENTO_SUCCESS: '@agendamento/UPDATE_ONE_SUCCESS',
  UPDATE_AGENDAMENTO_ERROR: '@agendamento/UPDATE_ONE_ERROR',

  // DELETE
  DELETE_AGENDAMENTO: '@agendamento/DELETE',
  DELETE_AGENDAMENTO_SUCCESS: '@agendamento/DELETE_SUCCESS',
  DELETE_AGENDAMENTO_ERROR: '@agendamento/DELETE_ERROR',
};

export default types;
